version: '3.8'
services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ../:/src/app
            - /src/app/node_modules
        environment:
            NODE_ENV: development
        restart: unless-stopped
# version: '3.8'
# services:
#     app:
#         build:
#             context: ..
#             dockerfile: docker/Dockerfile
#         ports:
#             - '3000:3000'
#         volumes:
#             - .:/src/app
#             - /src/app/node_modules
#         environment:
#             NODE_ENV: development
